### ISSUE TITLE
Support for 1.21.3

### ISSUE THREAD

**Issue by Mqxx** [pajicadvance/enchantmentdisabler#10]
Hey, first of all thanks for this mod! I am currently on the search for a survival vanilla friendly mod to use on my server. Can you port this mod to 1.21.3?

Thanks!

**Comment by pajicadvance** [comment]
Hi there, the only reason why the mod is not being updated yet is because a mod I depend on, JsonPatcher, hasn't updated to 1.21.3 yet. Once that happens, updating shouldn't take long.

**Comment by Mqxx** [comment]
Okay. Thanks for the quick response 😃
