### ISSUE TITLE
The mod doesn't work with Majrusz's Enchantments

### ISSUE THREAD

**Issue by Blob336** [pajicadvance/enchantmentdisabler#5]
After disabling some enchantments from [Majrusz's Enchantments](https://github.com/Majrusz/MajruszsEnchantmentsMod), they are still accesible via enchanting table.

_____________________________________________
Minecraft 1.20.1 with Fabric Loader 0.15.6
- enchantmentdisabler 0.1.4
- fabric-api 0.91.1+1.20.1
- majruszlibrary 7.0.5
- majruszsenchantments 1.10.6

**Comment by pajicadvance** [comment]
The mod seems to have its own way of registering enchantments to the game, and I'm not really interested in supporting custom systems like this.

But it appears that the mod has its own configuration where you can enable/disable enchantments from the mod - maybe try that out.
