### ISSUE TITLE
Feature request - Disabling certain enchant levels

### ISSUE THREAD

**Issue by anoomolu** [pajicadvance/enchantmentdisabler#6]
Hiya, first off this has mod been a really useful mod balancing my personal packs, so thank you for making it!

I was wondering if it'd be possible to limit the level of certain enchants? I'd like to nerf enchants across the board, such as Respiration to make Water Breathing pots more appealing, or general stat boost enchants ala Sharpness and Protection.

**Comment by pajicadvance** [comment]
Implemented this feature in the undergoing rewrite.
